package kr.gampa.battlegrounds.vehicle;

import java.util.*;
import kr.gampa.battlegrounds.BattlegroundsPlugin;
import kr.gampa.battlegrounds.item.ItemRegistry;
import net.kyori.adventure.text.Component;
import org.bukkit.*;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.entity.EntityDamageEvent;
import org.bukkit.event.player.*;
import org.bukkit.event.vehicle.VehicleExitEvent;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.util.Transformation;
import org.joml.Vector3f;

public final class VehicleManager implements Listener {
  private final BattlegroundsPlugin plugin; private final ItemRegistry items; private final NamespacedKey spawnKey,rootKey; private final Map<String,VehicleSpec> specs=new LinkedHashMap<>(); private final Map<UUID,VehicleInstance> instances=new HashMap<>();private final Map<UUID,Long> roadkillCooldown=new HashMap<>();
  public VehicleManager(BattlegroundsPlugin plugin,ItemRegistry items){this.plugin=plugin;this.items=items;spawnKey=new NamespacedKey(plugin,"vehicle_spawn_id");rootKey=new NamespacedKey(plugin,"vehicle_root");removeOrphans();reload();Bukkit.getScheduler().runTaskTimer(plugin,this::tick,1,1);}
  public void reload(){specs.clear();ConfigurationSection root=plugin.getConfig().getConfigurationSection("vehicles");if(root==null)return;for(String id:root.getKeys(false)){ConfigurationSection c=root.getConfigurationSection(id);specs.put(id,new VehicleSpec(id,VehicleType.valueOf(c.getString("type","LAND")),c.getDouble("top-speed-kmh"),c.getDouble("reverse-speed-kmh"),c.getDouble("turn-rate-deg"),c.getInt("seats"),c.getDouble("durability"),c.getDouble("fuel-capacity"),c.getDouble("acceleration"),c.getDouble("fuel-per-second"),c.getBoolean("armored")));}}
  public Set<String> ids(){return Collections.unmodifiableSet(specs.keySet());}
  public ItemStack spawnItem(String id){VehicleSpec spec=specs.get(id);if(spec==null)return null;ConfigurationSection c=config(id);ItemStack item=new ItemStack(Material.matchMaterial(c.getString("spawn-item","MINECART")));ItemMeta meta=item.getItemMeta();meta.displayName(Component.text("§e"+c.getString("name",id)+" 소환권"));meta.lore(List.of(Component.text("§7우클릭하여 이동수단을 배치합니다."),Component.text("§8"+id)));meta.getPersistentDataContainer().set(spawnKey,PersistentDataType.STRING,id);item.setItemMeta(meta);return item;}
  public boolean isSpawnItem(ItemStack item){return vehicleItemId(item)!=null;}
  public String vehicleItemId(ItemStack item){return item==null||!item.hasItemMeta()?null:item.getItemMeta().getPersistentDataContainer().get(spawnKey,PersistentDataType.STRING);}
  public Entity spawn(String id,Location at){VehicleSpec spec=specs.get(id);if(spec==null)return null;ArmorStand root=at.getWorld().spawn(at,ArmorStand.class,a->{a.setInvisible(true);a.setBasePlate(false);a.setArms(false);a.setGravity(spec.type()!=VehicleType.AIR);a.setCollidable(true);a.customName(Component.text("§e"+config(id).getString("name",id)));a.setCustomNameVisible(true);a.getPersistentDataContainer().set(rootKey,PersistentDataType.STRING,a.getUniqueId().toString());});VehicleInstance instance=new VehicleInstance(id,root,VehicleState.fresh(spec));ItemDisplay display=at.getWorld().spawn(at.clone().add(0,.3,0),ItemDisplay.class,d->{d.setItemStack(new ItemStack(Material.matchMaterial(config(id).getString("model-material","IRON_BLOCK"))));d.setItemDisplayTransform(ItemDisplay.ItemDisplayTransform.FIXED);Transformation t=d.getTransformation();List<Double> scale=config(id).getDoubleList("model-scale");if(scale.size()==3)t.getScale().set(new Vector3f(scale.get(0).floatValue(),scale.get(1).floatValue(),scale.get(2).floatValue()));d.setTransformation(t);d.getPersistentDataContainer().set(rootKey,PersistentDataType.STRING,root.getUniqueId().toString());});root.addPassenger(display);instance.visuals.add(display);for(int n=0;n<spec.seats();n++){ArmorStand seat=at.getWorld().spawn(at,ArmorStand.class,a->{a.setInvisible(true);a.setSmall(true);a.setBasePlate(false);a.setGravity(false);a.setCollidable(false);a.getPersistentDataContainer().set(rootKey,PersistentDataType.STRING,root.getUniqueId().toString());});instance.seats.add(seat);}instances.put(root.getUniqueId(),instance);return root;}
  private ConfigurationSection config(String id){return plugin.getConfig().getConfigurationSection("vehicles."+id);}

  @EventHandler(priority=EventPriority.HIGH) public void place(PlayerInteractEvent e){if(e.getHand()!=EquipmentSlot.HAND||!e.getAction().isRightClick())return;String id=vehicleItemId(e.getItem());if(id==null)return;e.setCancelled(true);Location at=e.getPlayer().getLocation().add(e.getPlayer().getLocation().getDirection().setY(0).normalize().multiply(2));if(!at.getBlock().isPassable()){e.getPlayer().sendMessage("차량을 배치할 공간이 없습니다.");return;}spawn(id,at);e.getItem().subtract();}
  @EventHandler public void interact(PlayerInteractAtEntityEvent e){VehicleInstance v=resolve(e.getRightClicked());if(v==null)return;e.setCancelled(true);String held=items.itemId(e.getPlayer().getInventory().getItemInMainHand());if("jerry-can".equals(held)){v.state=v.state.refuel(config(v.specId).getDouble("fuel-fill",60),specs.get(v.specId).fuelCapacity());e.getPlayer().getInventory().getItemInMainHand().subtract();e.getPlayer().sendMessage("연료를 보충했습니다.");return;}if("all-in-one-repair-kit".equals(held)){VehicleSpec s=specs.get(v.specId);v.state=new VehicleState(v.state.speedKmh(),v.state.fuel(),s.durability(),false);e.getPlayer().getInventory().getItemInMainHand().subtract();e.getPlayer().sendMessage("이동수단을 수리했습니다.");return;}VehicleSpec spec=specs.get(v.specId);ArmorStand seat=v.freeSeat();if(seat==null){e.getPlayer().sendMessage("빈 좌석이 없습니다.");return;}if(spec.armored()&&config(v.specId).getBoolean("locked-to-team")&&v.driver()!=null&&!sameTeam(v.driver(),e.getPlayer())){e.getPlayer().sendMessage("BRDM이 잠겨 있습니다.");return;}seat.addPassenger(e.getPlayer());}
  @EventHandler public void input(PlayerInputEvent e){if(e.getPlayer().getVehicle()==null)return;VehicleInstance v=resolve(e.getPlayer().getVehicle());if(v!=null&&v.driver()==e.getPlayer())v.updateInput(e.getInput());}
  @EventHandler(priority=EventPriority.HIGHEST) public void damage(EntityDamageEvent e){if(!instances.containsKey(e.getEntity().getUniqueId())&&!e.getEntity().getPersistentDataContainer().has(rootKey))return;VehicleInstance v=resolve(e.getEntity());if(v==null)return;e.setCancelled(true);double multiplier=specs.get(v.specId).armored()?.55:1;v.state=v.state.damage(e.getFinalDamage()*50*multiplier);if(v.state.destroyed())beginExplosion(v);}
  @EventHandler public void exit(VehicleExitEvent e){VehicleInstance v=resolve(e.getVehicle());if(v==null||!(e.getExited() instanceof Player p))return;double speed=Math.abs(v.state.speedKmh()),safe=plugin.getConfig().getDouble("vehicle-system.exit-safe-speed-kmh",30),lethal=plugin.getConfig().getDouble("vehicle-system.exit-lethal-speed-kmh",65);if(speed>safe){double pubgDamage=Math.min(100,(speed-safe)/(lethal-safe)*100);Bukkit.getScheduler().runTask(plugin,()->p.damage(pubgDamage/plugin.getConfig().getDouble("combat.health-scale",5)));}}
  @EventHandler public void quit(PlayerQuitEvent e){if(e.getPlayer().getVehicle()!=null)e.getPlayer().leaveVehicle();}

  private void tick(){long now=Bukkit.getCurrentTick();roadkillCooldown.entrySet().removeIf(x->now-x.getValue()>200);for(VehicleInstance v:new ArrayList<>(instances.values())){if(!v.root.isValid()){remove(v);continue;}if(v.exploding)continue;VehicleSpec spec=specs.get(v.specId);Player driver=v.driver();if(driver==null)v.input=new VehicleInput(0,0,false,false);detectCollision(v);v.state=VehiclePhysics.step(spec,v.state,v.input,.05);boolean water=v.root.getLocation().getBlock().isLiquid();double speed=VehiclePhysics.terrainSpeed(spec,v.state,water);double turnFactor=Math.min(1,Math.abs(speed)/20);v.heading+=v.input.steering()*spec.turnRateDeg()*.05*turnFactor*Math.signum(speed==0?1:speed);double radians=Math.toRadians(v.heading);org.bukkit.util.Vector velocity=new org.bukkit.util.Vector(-Math.sin(radians),v.root.getVelocity().getY(),Math.cos(radians)).multiply(speed/72d);if(water&&(spec.type()==VehicleType.WATER||spec.type()==VehicleType.AMPHIBIOUS))velocity.setY(.06);if(spec.type()==VehicleType.AIR){v.root.setGravity(false);double vertical=-.03;if(VehiclePhysics.canClimb(spec.type(),Math.abs(speed),config(v.specId).getDouble("takeoff-speed-kmh",60))){if(v.input.boost())vertical=.16;else if(v.input.brake())vertical=-.16;else vertical=0;}velocity.setY(vertical);}v.root.setRotation(v.heading,0);v.root.setVelocity(velocity);updateSeats(v);roadkill(v,speed);v.lastLocation=v.root.getLocation();v.lastCommandedKmh=speed;if(driver!=null&&plugin.getConfig().getBoolean("vehicle-system.show-actionbar",true)){double fuelPct=spec.fuelCapacity()==0?100:v.state.fuel()/spec.fuelCapacity()*100;driver.sendActionBar(Component.text(String.format("속도 %.0f km/h  연료 %.0f%%  내구도 %.0f/%.0f",Math.abs(speed),fuelPct,v.state.durability(),spec.durability())));}}}
  private void updateSeats(VehicleInstance v){Location base=v.root.getLocation();double rad=Math.toRadians(v.heading);for(int i=0;i<v.seats.size();i++){double side=(i%2==0?-.45:.45),back=-(i/2)*.8;double x=side*Math.cos(rad)-back*Math.sin(rad),z=side*Math.sin(rad)+back*Math.cos(rad);ArmorStand seat=v.seats.get(i);if(seat.isValid())seat.teleport(base.clone().add(x,.15,z).setDirection(base.getDirection()));}}
  private void detectCollision(VehicleInstance v){if(v.lastLocation==null||v.lastLocation.getWorld()!=v.root.getWorld())return;double expected=Math.abs(v.lastCommandedKmh)/72d,actual=Math.hypot(v.root.getLocation().getX()-v.lastLocation.getX(),v.root.getLocation().getZ()-v.lastLocation.getZ());long tick=Bukkit.getCurrentTick();if(expected>.28&&actual<expected*.25&&tick-v.lastCollisionTick>10){double damage=VehiclePhysics.collisionDamage(Math.abs(v.lastCommandedKmh),plugin.getConfig().getDouble("vehicle-system.collision-damage-multiplier",1));v.state=v.state.damage(damage);v.lastCollisionTick=tick;if(v.state.destroyed())beginExplosion(v);}}
  private void roadkill(VehicleInstance v,double speed){if(Math.abs(speed)<plugin.getConfig().getDouble("vehicle-system.roadkill-min-speed-kmh",25))return;long tick=Bukkit.getCurrentTick();for(Entity e:v.root.getNearbyEntities(1.4,1.2,1.4)){Long last=roadkillCooldown.get(e.getUniqueId());if(!(e instanceof LivingEntity living)||v.isOccupant(e)||resolve(e)!=null||(last!=null&&tick-last<10))continue;roadkillCooldown.put(e.getUniqueId(),tick);living.damage(Math.abs(speed)/plugin.getConfig().getDouble("combat.health-scale",5),v.driver());}}
  private void beginExplosion(VehicleInstance v){if(v.exploding)return;v.exploding=true;v.root.getWorld().playSound(v.root.getLocation(),Sound.BLOCK_FIRE_AMBIENT,2,1);long delay=(long)(config(v.specId).getDouble("explosion-delay-seconds",5)*20);Bukkit.getScheduler().runTaskLater(plugin,()->explode(v),delay);}
  private void explode(VehicleInstance v){if(!v.root.isValid())return;Location at=v.root.getLocation();double radius=config(v.specId).getDouble("explosion-radius",5);for(Entity e:at.getWorld().getNearbyEntities(at,radius,radius,radius))if(e instanceof LivingEntity living)living.damage(Math.max(0,100*(1-e.getLocation().distance(at)/radius))/plugin.getConfig().getDouble("combat.health-scale",5));at.getWorld().spawnParticle(Particle.EXPLOSION,at,3);at.getWorld().playSound(at,Sound.ENTITY_GENERIC_EXPLODE,3,.7f);remove(v);}
  private void remove(VehicleInstance v){for(ArmorStand seat:v.seats)seat.remove();for(Entity visual:v.visuals)visual.remove();v.root.remove();instances.remove(v.id);}
  public void shutdown(){for(VehicleInstance v:new ArrayList<>(instances.values()))remove(v);}
  private void removeOrphans(){for(World world:Bukkit.getWorlds())for(Entity e:world.getEntities())if(e.getPersistentDataContainer().has(rootKey))e.remove();}
  private VehicleInstance resolve(Entity entity){if(entity==null)return null;if(instances.containsKey(entity.getUniqueId()))return instances.get(entity.getUniqueId());String raw=entity.getPersistentDataContainer().get(rootKey,PersistentDataType.STRING);if(raw==null&&entity.getVehicle()!=null)return resolve(entity.getVehicle());try{return instances.get(UUID.fromString(raw));}catch(Exception ex){return null;}}
  private boolean sameTeam(Player a,Player b){var team=a.getScoreboard().getEntryTeam(a.getName());return team!=null&&team.equals(b.getScoreboard().getEntryTeam(b.getName()));}
}
